#include <boost/test/minimal.hpp>

#include <trance/typeinfo.hpp>

int
test_main( int, char *[] )
{
    BOOST_REQUIRE( TRANCE_TYPEID( int ) == TRANCE_TYPEID( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID( 0 ) == TRANCE_TYPEID( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID( int ) == TRANCE_TYPEID( 0 ) );
    BOOST_REQUIRE( TRANCE_TYPEID( 0 ) == TRANCE_TYPEID( 0 ) );

    BOOST_REQUIRE( TRANCE_TYPEID( int ) == TRANCE_TYPEID_BY_EXPR( 0 ) );
    BOOST_REQUIRE( TRANCE_TYPEID( 0 ) == TRANCE_TYPEID_BY_EXPR( 0 ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_EXPR( 0 ) == TRANCE_TYPEID( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_EXPR( 0 ) == TRANCE_TYPEID( 0 ) );

    BOOST_REQUIRE( TRANCE_TYPEID( int ) == TRANCE_TYPEID_BY_TYPE( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID( 0 ) == TRANCE_TYPEID_BY_TYPE( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_TYPE( int ) == TRANCE_TYPEID( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_TYPE( int ) == TRANCE_TYPEID( 0 ) );

    BOOST_REQUIRE( TRANCE_TYPEID_BY_EXPR( 0 ) == TRANCE_TYPEID_BY_EXPR( 0 ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_EXPR( 0 ) == TRANCE_TYPEID_BY_TYPE( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_TYPE( int ) == TRANCE_TYPEID_BY_EXPR( 0 ) );

    BOOST_REQUIRE( TRANCE_TYPEID_BY_TYPE( int ) == TRANCE_TYPEID_BY_TYPE( int ) );

    BOOST_REQUIRE( TRANCE_TYPEID( double) != TRANCE_TYPEID( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID( 0.0 ) != TRANCE_TYPEID( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID( double ) != TRANCE_TYPEID( 0 ) );
    BOOST_REQUIRE( TRANCE_TYPEID( 0.0 ) != TRANCE_TYPEID( 0 ) );

    BOOST_REQUIRE( TRANCE_TYPEID( double ) != TRANCE_TYPEID_BY_EXPR( 0 ) );
    BOOST_REQUIRE( TRANCE_TYPEID( 0.0 ) != TRANCE_TYPEID_BY_EXPR( 0 ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_EXPR( 0.0 ) != TRANCE_TYPEID( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_EXPR( 0.0 ) != TRANCE_TYPEID( 0 ) );

    BOOST_REQUIRE( TRANCE_TYPEID( double ) != TRANCE_TYPEID_BY_TYPE( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID( 0.0 ) != TRANCE_TYPEID_BY_TYPE( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_TYPE( double ) != TRANCE_TYPEID( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_TYPE( double ) != TRANCE_TYPEID( 0 ) );

    BOOST_REQUIRE( TRANCE_TYPEID_BY_EXPR( 0.0 ) != TRANCE_TYPEID_BY_EXPR( 0 ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_EXPR( 0.0 ) != TRANCE_TYPEID_BY_TYPE( int ) );
    BOOST_REQUIRE( TRANCE_TYPEID_BY_TYPE( double ) != TRANCE_TYPEID_BY_EXPR( 0 ) );

    BOOST_REQUIRE( TRANCE_TYPEID_BY_TYPE( double ) != TRANCE_TYPEID_BY_TYPE( int ) );

    return 0;
}

